# Welcome to Jekyll!

# Website settings
title: Nahalco
description: Lian Smart Cloud based Monitoring (Nahal)
keywords: nahalco
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://nahalco.net/  # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
